# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#

# ======= SQLite使用時の設定 =======

default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

# ======= Postgres使用時の設定 =======
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see Rails configuration guide
#   # https://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   # host: dbという設定は、Dockerコンテナ内で実行されているPostgreSQLサーバーに接続することを意味しています。
#   host: db
#   # データベース名を決める（記述なしならデフォルトでpostgres）
#   # database: my_database
#   username: <%= ENV["POSTGRES_USER"] %>
#   password: <%= ENV["POSTGRES_PASSWORD"] %>
  
# development:
#   <<: *default
#   database: app_development

# test:
#   <<: *default
#   database: app_test

# production:
#   <<: *default
#   database: app_production
